//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Chebotarev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public int id { get; set; }
        public int number_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public Nullable<System.DateTime> departure_name { get; set; }
    
        public virtual Room_stock Room_stock { get; set; }
        public virtual Users Users { get; set; }
    }
}
