//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Chebotarev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room_stock()
        {
            this.Guests = new HashSet<Guests>();
        }
    
        public int number { get; set; }
        public int category_id { get; set; }
        public int floor_id { get; set; }
        public int status_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Floors Floors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guests> Guests { get; set; }
        public virtual Room_status Room_status { get; set; }
    }
}
